DROP TABLE `SHT`.`WMT_CST_STRG`;

CREATE TABLE `SHT`.`WMT_CST_STRG`
(
    `WH_CD`    VARCHAR(20) NOT NULL
 COMMENT '창고코드',
    `LOT_NO`    VARCHAR(20) NOT NULL
 COMMENT 'LOT번호',
    `CELL_NO`    VARCHAR(20) NOT NULL
 COMMENT '셀번호',
    `INVN_QTY`    DECIMAL DEFAULT 0 NOT NULL
 COMMENT '재고수량',
    `AVLB_QTY`    DECIMAL DEFAULT 0 NOT NULL
 COMMENT '가용수량',
    `ALLOC_QTY`    DECIMAL DEFAULT 0 NOT NULL
 COMMENT '할당수량',
    `HLD_QTY`    DECIMAL DEFAULT 0 NOT NULL
 COMMENT '보류수량',
    `INS_USER_ID`    VARCHAR(20) NOT NULL
 COMMENT '입력사용자ID',
    `INS_DATETIME`    CHAR(14) NOT NULL
 COMMENT '입력일시',
    `UPD_USER_ID`    VARCHAR(20) NOT NULL
 COMMENT '수정사용자ID',
    `UPD_DATETIME`    CHAR(14) NOT NULL
 COMMENT '수정일시'
)
 COMMENT = '재고';

ALTER TABLE `WMT_CST_STRG`
 ADD CONSTRAINT `WMT_CST_STRG_CELL_ITEM_LOT_PK` PRIMARY KEY ( `WH_CD`,`LOT_NO`,`CELL_NO` );

SELECT 
    WH_CD,
    LOT_NO,
    CELL_NO,
    INVN_QTY,
    AVLB_QTY,
    ALLOC_QTY,
    HLD_QTY,
    INS_USER_ID,
    INS_DATETIME,
    UPD_USER_ID,
    UPD_DATETIME
FROM WMT_CST_STRG;

INSERT INTO WMT_CST_STRG(WH_CD,LOT_NO,CELL_NO,INVN_QTY,AVLB_QTY,ALLOC_QTY,HLD_QTY,INS_USER_ID,INS_DATETIME,UPD_USER_ID,UPD_DATETIME)
    VALUES('WH','LOT','CELL',20,10,7,3,'sklee','20250824200000','sklee','20250824200000');
